#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$manifest = json_decode(file_get_contents(__DIR__.'/composer.json'), true);

$app = new Symfony\Component\Console\Application('Dusk Updater', $manifest['version'] ?? '1.x-dev');

$app->add(new Orchestra\DuskUpdater\DetectCommand());
$app->add(new Orchestra\DuskUpdater\UpdateCommand());

$app->run();
